"""initial schema

Revision ID: 291ef7c1f38d
Revises: 
Create Date: 2026-05-07 11:30:54.681532

"""
from typing import Sequence, Union

from alembic import op
from qdrant_loader.core.state.models import UTCDateTime
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291ef7c1f38d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('cursor_kind', sa.String(), nullable=False),
    sa.Column('cursor_value', sa.String(), nullable=True),
    sa.Column('batch_index', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_type', 'source', name='uq_ingestion_checkpoint_source')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_name', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_name', name='uix_project_collection')
    )
    op.create_index('ix_project_display_name', 'projects', ['display_name'], unique=False)
    op.create_table('document_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', qdrant_loader.core.state.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', qdrant_loader.core.state.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_converted', sa.Boolean(), nullable=True),
    sa.Column('conversion_method', sa.String(), nullable=True),
    sa.Column('original_file_type', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('conversion_failed', sa.Boolean(), nullable=True),
    sa.Column('conversion_error', sa.Text(), nullable=True),
    sa.Column('conversion_time', sa.Float(), nullable=True),
    sa.Column('is_attachment', sa.Boolean(), nullable=True),
    sa.Column('parent_document_id', sa.String(), nullable=True),
    sa.Column('attachment_id', sa.String(), nullable=True),
    sa.Column('attachment_filename', sa.String(), nullable=True),
    sa.Column('attachment_mime_type', sa.String(), nullable=True),
    sa.Column('attachment_download_url', sa.String(), nullable=True),
    sa.Column('attachment_author', sa.String(), nullable=True),
    sa.Column('attachment_created_at', qdrant_loader.core.state.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_type', 'source', 'document_id', name='uix_project_document')
    )
    op.create_index('ix_document_attachment', 'document_states', ['is_attachment'], unique=False)
    op.create_index('ix_document_conversion_method', 'document_states', ['conversion_method'], unique=False)
    op.create_index('ix_document_converted', 'document_states', ['is_converted'], unique=False)
    op.create_index('ix_document_parent', 'document_states', ['parent_document_id'], unique=False)
    op.create_index('ix_document_project_id', 'document_states', ['project_id'], unique=False)
    op.create_index('ix_document_uri', 'document_states', ['uri'], unique=True)
    op.create_index('ix_document_url', 'document_states', ['url'], unique=False)
    op.create_table('ingestion_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_successful_ingestion', qdrant_loader.core.state.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', qdrant_loader.core.state.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', qdrant_loader.core.state.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('converted_files_count', sa.Integer(), nullable=True),
    sa.Column('conversion_failures_count', sa.Integer(), nullable=True),
    sa.Column('attachments_processed_count', sa.Integer(), nullable=True),
    sa.Column('total_conversion_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_type', 'source', name='uix_project_source_ingestion')
    )
    op.create_index('ix_ingestion_project_id', 'ingestion_history', ['project_id'], unique=False)
    op.create_table('project_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('last_sync_time', qdrant_loader.core.state.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', qdrant_loader.core.state.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', qdrant_loader.core.state.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_type', 'source_name', name='uix_project_source')
    )
    op.create_index('ix_project_source_status', 'project_sources', ['status'], unique=False)
    op.create_index('ix_project_source_type', 'project_sources', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_source_type', table_name='project_sources')
    op.drop_index('ix_project_source_status', table_name='project_sources')
    op.drop_table('project_sources')
    op.drop_index('ix_ingestion_project_id', table_name='ingestion_history')
    op.drop_table('ingestion_history')
    op.drop_index('ix_document_url', table_name='document_states')
    op.drop_index('ix_document_uri', table_name='document_states')
    op.drop_index('ix_document_project_id', table_name='document_states')
    op.drop_index('ix_document_parent', table_name='document_states')
    op.drop_index('ix_document_converted', table_name='document_states')
    op.drop_index('ix_document_conversion_method', table_name='document_states')
    op.drop_index('ix_document_attachment', table_name='document_states')
    op.drop_table('document_states')
    op.drop_index('ix_project_display_name', table_name='projects')
    op.drop_table('projects')
    op.drop_table('ingestion_checkpoints')
    # ### end Alembic commands ###
